[versions]
core-kotlin = "1.9.23"
core-ktor = "2.3.10"

netty-logback = "1.5.6"

koin = "3.5.6"

firebase = "9.2.0"

[libraries]

#ktor
ktor-core-jvm = { module = "io.ktor:ktor-server-core-jvm" }
ktor-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }

#firebase
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebase" }

#netty
netty-logback = { module = "ch.qos.logback:logback-classic", version.ref = "netty-logback" }

#koin
koin = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }